// Git Panel Component for AutoWebIQ
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { 
  GitBranch, 
  GitCommit, 
  GitMerge, 
  Upload, 
  Download,
  CheckCircle,
  Circle,
  RefreshCw,
  Github
} from 'lucide-react';

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL || 'http://localhost:8001';

const GitPanel = ({ projectId }) => {
  const [status, setStatus] = useState(null);
  const [history, setHistory] = useState([]);
  const [branches, setBranches] = useState([]);
  const [commitMessage, setCommitMessage] = useState('');
  const [loading, setLoading] = useState(false);
  const [showGitHubDialog, setShowGitHubDialog] = useState(false);
  const [githubToken, setGithubToken] = useState('');
  const [repoName, setRepoName] = useState('');

  useEffect(() => {
    loadGitStatus();
    loadCommitHistory();
    loadBranches();
  }, [projectId]);

  const loadGitStatus = async () => {
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get(
        `${BACKEND_URL}/api/git/${projectId}/status`,
        { headers: { Authorization: `Bearer ${token}` } }
      );

      if (response.data.status === 'success') {
        setStatus(response.data);
      }
    } catch (err) {
      console.error('Failed to load git status:', err);
    }
  };

  const loadCommitHistory = async () => {
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get(
        `${BACKEND_URL}/api/git/${projectId}/history`,
        { headers: { Authorization: `Bearer ${token}` } }
      );

      if (response.data.status === 'success') {
        setHistory(response.data.commits || []);
      }
    } catch (err) {
      console.error('Failed to load commit history:', err);
    }
  };

  const loadBranches = async () => {
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get(
        `${BACKEND_URL}/api/git/${projectId}/branches`,
        { headers: { Authorization: `Bearer ${token}` } }
      );

      if (response.data.status === 'success') {
        setBranches(response.data.branches || []);
      }
    } catch (err) {
      console.error('Failed to load branches:', err);
    }
  };

  const handleInitGit = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem('token');
      const response = await axios.post(
        `${BACKEND_URL}/api/git/init`,
        { project_id: projectId },
        { headers: { Authorization: `Bearer ${token}` } }
      );

      if (response.data.status === 'success') {
        alert('Git initialized successfully!');
        loadGitStatus();
      }
    } catch (err) {
      alert('Failed to initialize git: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleCommit = async () => {
    if (!commitMessage.trim()) {
      alert('Please enter a commit message');
      return;
    }

    setLoading(true);
    try {
      const token = localStorage.getItem('token');
      const response = await axios.post(
        `${BACKEND_URL}/api/git/commit`,
        {
          project_id: projectId,
          message: commitMessage,
          files: null // Stage all files
        },
        { headers: { Authorization: `Bearer ${token}` } }
      );

      if (response.data.status === 'success' || response.data.status === 'info') {
        alert('Committed successfully!');
        setCommitMessage('');
        loadGitStatus();
        loadCommitHistory();
      }
    } catch (err) {
      alert('Failed to commit: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const handlePushToGitHub = async () => {
    if (!githubToken || !repoName) {
      alert('Please provide GitHub token and repository name');
      return;
    }

    setLoading(true);
    try {
      const token = localStorage.getItem('token');
      const response = await axios.post(
        `${BACKEND_URL}/api/git/github/create-repo`,
        {
          project_id: projectId,
          github_token: githubToken,
          repo_name: repoName,
          description: 'Generated by AutoWebIQ',
          private: false
        },
        { headers: { Authorization: `Bearer ${token}` } }
      );

      if (response.data.status === 'success') {
        alert('Code pushed to GitHub successfully!\nRepo: ' + response.data.repo_url);
        setShowGitHubDialog(false);
        setGithubToken('');
        setRepoName('');
      }
    } catch (err) {
      alert('Failed to push to GitHub: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  if (!status) {
    return (
      <div className="h-full flex flex-col items-center justify-center bg-gray-900 text-gray-400 p-8">
        <GitBranch className="w-16 h-16 mb-4 text-gray-600" />
        <p className="mb-4">Git not initialized</p>
        <button
          onClick={handleInitGit}
          disabled={loading}
          className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded"
        >
          Initialize Git
        </button>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col bg-gray-900">
      {/* Header */}
      <div className="bg-gray-800 px-4 py-3 border-b border-gray-700">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <GitBranch className="w-5 h-5 text-green-400" />
            <span className="text-white font-semibold">
              {status.branch || 'main'}
            </span>
          </div>
          <button
            onClick={loadGitStatus}
            className="p-1 hover:bg-gray-700 rounded"
          >
            <RefreshCw className="w-4 h-4 text-gray-400" />
          </button>
        </div>
      </div>

      {/* Changes */}
      <div className="flex-1 overflow-y-auto p-4">
        <div className="mb-6">
          <h3 className="text-white font-semibold mb-2 flex items-center space-x-2">
            <Circle className="w-4 h-4" />
            <span>Changes</span>
          </h3>
          {status.clean ? (
            <p className="text-gray-400 text-sm">No changes</p>
          ) : (
            <div className="space-y-2">
              {status.modified?.map(file => (
                <div key={file} className="text-sm text-yellow-400 flex items-center space-x-2">
                  <Circle className="w-3 h-3" />
                  <span>{file}</span>
                </div>
              ))}
              {status.untracked?.map(file => (
                <div key={file} className="text-sm text-green-400 flex items-center space-x-2">
                  <Circle className="w-3 h-3" />
                  <span>{file}</span>
                </div>
              ))}
              {status.staged?.map(file => (
                <div key={file} className="text-sm text-blue-400 flex items-center space-x-2">
                  <CheckCircle className="w-3 h-3" />
                  <span>{file}</span>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Commit */}
        {!status.clean && (
          <div className="mb-6">
            <h3 className="text-white font-semibold mb-2">Commit Changes</h3>
            <textarea
              value={commitMessage}
              onChange={(e) => setCommitMessage(e.target.value)}
              placeholder="Commit message..."
              className="w-full bg-gray-800 text-white rounded px-3 py-2 mb-2 text-sm"
              rows={3}
            />
            <button
              onClick={handleCommit}
              disabled={loading || !commitMessage.trim()}
              className="w-full px-4 py-2 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-700 text-white rounded text-sm"
            >
              Commit
            </button>
          </div>
        )}

        {/* Push to GitHub */}
        <div className="mb-6">
          <button
            onClick={() => setShowGitHubDialog(true)}
            className="w-full px-4 py-2 bg-gray-800 hover:bg-gray-700 text-white rounded flex items-center justify-center space-x-2"
          >
            <Github className="w-4 h-4" />
            <span>Push to GitHub</span>
          </button>
        </div>

        {/* History */}
        <div>
          <h3 className="text-white font-semibold mb-2 flex items-center space-x-2">
            <GitCommit className="w-4 h-4" />
            <span>Recent Commits</span>
          </h3>
          {history.length === 0 ? (
            <p className="text-gray-400 text-sm">No commits yet</p>
          ) : (
            <div className="space-y-3">
              {history.map(commit => (
                <div key={commit.hash} className="bg-gray-800 rounded p-3">
                  <div className="text-white text-sm mb-1">{commit.message}</div>
                  <div className="text-gray-400 text-xs">
                    {commit.author} • {commit.hash.substring(0, 7)}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* GitHub Dialog */}
      {showGitHubDialog && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-gray-800 rounded-lg p-6 w-96">
            <h2 className="text-white text-lg font-semibold mb-4">Push to GitHub</h2>
            <div className="space-y-4">
              <div>
                <label className="text-gray-400 text-sm block mb-1">
                  GitHub Token
                </label>
                <input
                  type="password"
                  value={githubToken}
                  onChange={(e) => setGithubToken(e.target.value)}
                  className="w-full bg-gray-700 text-white rounded px-3 py-2"
                  placeholder="ghp_..."
                />
              </div>
              <div>
                <label className="text-gray-400 text-sm block mb-1">
                  Repository Name
                </label>
                <input
                  type="text"
                  value={repoName}
                  onChange={(e) => setRepoName(e.target.value)}
                  className="w-full bg-gray-700 text-white rounded px-3 py-2"
                  placeholder="my-awesome-project"
                />
              </div>
              <div className="flex space-x-2">
                <button
                  onClick={handlePushToGitHub}
                  disabled={loading}
                  className="flex-1 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded"
                >
                  Push
                </button>
                <button
                  onClick={() => setShowGitHubDialog(false)}
                  className="flex-1 px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default GitPanel;