import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Sparkles, ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import '../styles/Terms.css';

const TermsOfService = () => {
  const navigate = useNavigate();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="terms-page">
      {/* Navigation */}
      <nav className="terms-nav">
        <div className="nav-content">
          <div className="brand" onClick={() => navigate('/')}>
            <div className="brand-icon">
              <Sparkles size={28} />
            </div>
            <span className="brand-name">AutoWebIQ</span>
          </div>
          <Button className="back-btn" onClick={() => navigate('/')}>
            <ArrowLeft size={18} />
            Back to Home
          </Button>
        </div>
      </nav>

      {/* Content */}
      <div className="terms-container">
        <div className="terms-content">
          <h1 className="terms-title">AutoWebIQ Inc. – Terms of Service</h1>
          
          <section className="terms-section">
            <h2>1. Introduction</h2>
            
            <h3>1.1 Agreement Overview</h3>
            <p>These Terms of Service ("Terms") constitute a legal agreement between you and AutoWebIQ Inc. ("we," "our," or "us"). Your use of autowebiq.com (the "Site") and related AI-powered web development services (collectively, the "Services") is subject to these Terms.</p>
            
            <p>By downloading, installing, accessing, or using our Services, you:</p>
            <ul>
              <li>Acknowledge that you have read and understood these Terms</li>
              <li>Agree to be bound by these Terms</li>
              <li>Agree to our Privacy Policy (available at autowebiq.com/privacy)</li>
              <li>Commit to comply with all applicable laws and regulations</li>
            </ul>
            
            <p>If you do not agree with these Terms, you must not download, install, access, or use our Services.</p>
            
            <h3>1.2 Definitions</h3>
            <ul>
              <li><strong>"Site"</strong> means our website and associated AI-powered tools for generating and deploying websites or software.</li>
              <li><strong>"Content"</strong> means all code, projects, data, files, or other materials you create, modify, or access through our Services.</li>
              <li><strong>"User"</strong> means any individual who accesses or uses our Services.</li>
              <li><strong>"Authorized User"</strong> means a User authorized by you to use our Services under your account.</li>
              <li><strong>"Input"</strong> means the prompts, commands, and instructions you provide.</li>
              <li><strong>"Output"</strong> means the code, website, or other materials generated by our AI systems based on your Input.</li>
            </ul>
          </section>

          <section className="terms-section">
            <h2>2. License to Use Our Services</h2>
            
            <h3>2.1 Rights Granted</h3>
            <p>Subject to your compliance with these Terms, AutoWebIQ grants you a limited, personal, non-exclusive, non-transferable license to use our Services for their intended purpose.</p>
            <p>Depending on your plan:</p>
            <ul>
              <li><strong>Free Plan:</strong> For personal, non-commercial use only.</li>
              <li><strong>Paid Plans:</strong> May be used for commercial or professional use as per your subscription terms.</li>
            </ul>
            
            <h3>2.2 Restrictions</h3>
            <p>You may not:</p>
            <ul>
              <li>Sell, rent, or sublicense our Services</li>
              <li>Remove any copyright or proprietary notices</li>
              <li>Use automated bots to scrape or abuse our Services</li>
              <li>Reverse engineer or modify any part of our platform</li>
              <li>Use the Services for unlawful purposes or to harm others</li>
            </ul>
            
            <h3>2.3 Reservation of Rights</h3>
            <p>All rights not expressly granted are reserved by AutoWebIQ. You do not acquire ownership of the Services by using them.</p>
          </section>

          <section className="terms-section">
            <h2>3. User Accounts and Content</h2>
            
            <h3>3.1 Account Creation and Management</h3>
            <ul>
              <li>You may need to create an account to access certain features.</li>
              <li>You must provide accurate, up-to-date information.</li>
              <li>You are responsible for maintaining account security.</li>
              <li>You must notify us immediately of unauthorized access or usage.</li>
            </ul>
            
            <h3>3.2 Minimum Age</h3>
            <p>You must be at least 13 years old to use our Services. If under 18, a parent or guardian must consent to your use. Guardians are responsible for the minor's activity on the platform.</p>
            
            <h3>3.3 Account Deletion</h3>
            <p>To delete your account, contact support@autowebiq.com.</p>
            <p>Upon deletion:</p>
            <ul>
              <li>Your profile and stored data will be removed within 90 days.</li>
              <li>Certain information may be retained as required by law.</li>
            </ul>
            
            <h3>3.4 User Content</h3>
            <p>You retain full ownership of all Content you create using AutoWebIQ.</p>
            
            <h3>3.5 License to User Content</h3>
            <p>You grant AutoWebIQ a non-exclusive, worldwide, royalty-free license to use your Content only as necessary to:</p>
            <ul>
              <li>Provide and maintain the Services</li>
              <li>Diagnose and resolve issues</li>
              <li>Comply with legal obligations</li>
            </ul>
            <p>We do not sell or publicly distribute your Content.</p>
            
            <h3>3.6 Backups</h3>
            <p>You are responsible for backing up your projects. We take precautions, but data loss is possible.</p>
          </section>

          <section className="terms-section">
            <h2>4. Services and Pricing</h2>
            
            <h3>4.1 Plans and Limits</h3>
            <p>AutoWebIQ offers various plans listed at autowebiq.com/pricing, each with usage limits such as:</p>
            <ul>
              <li>Number of projects or AI generations</li>
              <li>Storage capacity</li>
              <li>Compute resources</li>
            </ul>
            <p>We may update pricing or limits periodically.</p>
            
            <h3>4.2 Payment Terms</h3>
            <ul>
              <li>Subscription billing is monthly or annual.</li>
              <li>Auto-renewal applies unless canceled.</li>
              <li>Payments are non-refundable unless stated otherwise.</li>
              <li>Failed payments may result in suspension or termination.</li>
            </ul>
            
            <h3>4.3 Support</h3>
            <ul>
              <li><strong>Free Plan:</strong> Limited community support</li>
              <li><strong>Paid Plan:</strong> Priority support</li>
              <li><strong>Enterprise Plan:</strong> Dedicated manager and SLA support</li>
            </ul>
            
            <h3>4.4 Service Delivery</h3>
            <p>Access begins immediately after successful payment.</p>
            <p>In case of issues, contact support@autowebiq.com.</p>
            <p>We aim for 99% uptime but cannot guarantee uninterrupted service.</p>
            
            <h3>4.5 Refund Policy</h3>
            <p>Refunds may be approved only in cases of:</p>
            <ul>
              <li>Duplicate charges</li>
              <li>Billing errors</li>
            </ul>
            <p>Requests are reviewed within 14 business days.</p>
            
            <h3>4.6 Cancellation</h3>
            <p>To cancel:</p>
            <ol>
              <li>Go to Billing Settings</li>
              <li>Click "Cancel Subscription"</li>
            </ol>
            <p>Your plan remains active until the end of your billing cycle.</p>
            <p>Unused credits expire upon cancellation.</p>
          </section>

          <section className="terms-section">
            <h2>5. Acceptable Use Policy</h2>
            
            <h3>5.1 Prohibited Activities</h3>
            <p>You agree not to:</p>
            <ul>
              <li>Violate any law</li>
              <li>Infringe on copyrights or trademarks</li>
              <li>Upload harmful code</li>
              <li>Bypass our system limits</li>
              <li>Abuse API or compute resources</li>
            </ul>
            
            <h3>5.2 Content Restrictions</h3>
            <p>Do not use AutoWebIQ to generate or distribute content that is:</p>
            <ul>
              <li>Illegal, abusive, or harassing</li>
              <li>Pornographic or violent</li>
              <li>Malicious or fraudulent</li>
            </ul>
            
            <h3>5.3 Resource Usage</h3>
            <p>Overuse may result in throttling or suspension.</p>
            
            <h3>5.4 Export Compliance</h3>
            <p>You agree not to use AutoWebIQ in violation of U.S. or international export laws or sanctions.</p>
          </section>

          <section className="terms-section">
            <h2>6. Data Usage and AI Training</h2>
            
            <h3>6.1 Improvement and Analytics</h3>
            <p>We collect usage data (e.g., performance metrics, prompt patterns) to enhance system performance.</p>
            
            <h3>6.2 AI Training</h3>
            <ul>
              <li>Your private data is not used for general AI model training without consent.</li>
              <li>Enterprise users can opt out of all data collection for training.</li>
            </ul>
            
            <h3>6.3 Bias Acknowledgment</h3>
            <p>AI outputs may contain biases inherent in training data. You are responsible for reviewing generated results before use.</p>
            
            <h3>6.4 Enterprise Data Protection</h3>
            <p>Enterprise users enjoy additional data handling options, including:</p>
            <ul>
              <li>Custom residency controls</li>
              <li>No third-party sharing without consent</li>
              <li>Dedicated data protection support</li>
            </ul>
          </section>

          <section className="terms-section">
            <h2>7. Intellectual Property Rights</h2>
            
            <h3>7.1 Ownership</h3>
            <p>AutoWebIQ Inc. owns:</p>
            <ul>
              <li>The platform design and architecture</li>
              <li>Logos, brand name, and trademarks</li>
              <li>Underlying algorithms and system software</li>
            </ul>
            
            <h3>7.2 User Rights</h3>
            <p>You retain ownership of:</p>
            <ul>
              <li>Generated websites and code</li>
              <li>Applications you build</li>
              <li>Custom configurations and designs</li>
            </ul>
            
            <h3>7.3 Usage Rights</h3>
            <p>You may use generated code freely for:</p>
            <ul>
              <li>Commercial projects</li>
              <li>Open-source releases</li>
              <li>Resale and redistribution</li>
            </ul>
            <p>AutoWebIQ claims no ownership over your generated projects.</p>
          </section>

          <section className="terms-section">
            <h2>8. Security and Privacy</h2>
            
            <h3>8.1 Security Measures</h3>
            <p>We use encryption, secure authentication, and regular audits. However, no system is perfectly secure.</p>
            
            <h3>8.2 Personal Data</h3>
            <p>Your personal data is processed as described in our Privacy Policy at autowebiq.com/privacy.</p>
            
            <h3>8.3 Data Processing Agreement</h3>
            <p>If required by GDPR or other data laws, you may request a DPA by emailing support@autowebiq.com.</p>
          </section>

          <section className="terms-section">
            <h2>9. Term and Termination</h2>
            
            <h3>9.1 Term</h3>
            <p>These Terms apply from your first use of the Services until terminated.</p>
            
            <h3>9.2 Termination by You</h3>
            <p>You may terminate your account anytime.</p>
            
            <h3>9.3 Termination by AutoWebIQ</h3>
            <p>We may suspend or terminate if:</p>
            <ul>
              <li>You violate these Terms</li>
              <li>Payments fail</li>
              <li>We discontinue the Service</li>
            </ul>
            
            <h3>9.4 Effect of Termination</h3>
            <p>Upon termination:</p>
            <ul>
              <li>Your license ends</li>
              <li>Account and data are deleted within 90 days</li>
              <li>No refunds are issued</li>
            </ul>
            
            <h3>9.5 Survival</h3>
            <p>Sections such as Intellectual Property, Limitation of Liability, and Indemnification survive termination.</p>
          </section>

          <section className="terms-section">
            <h2>10. Disclaimer of Warranties</h2>
            <p>Your use of AutoWebIQ is at your own risk.</p>
            <p>The Services are provided "AS IS" and "AS AVAILABLE."</p>
            <p>We do not guarantee that AI-generated code will be accurate, error-free, or secure.</p>
            <p>We disclaim all implied warranties, including merchantability and fitness for a particular purpose.</p>
          </section>

          <section className="terms-section">
            <h2>11. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law:</p>
            <p>AutoWebIQ and its affiliates are not liable for indirect, incidental, or consequential damages, including loss of profits, data, or business opportunities.</p>
            <p>Total liability for all claims will not exceed the total amount you paid to AutoWebIQ in the 12 months preceding the claim.</p>
          </section>

          <section className="terms-section">
            <h2>12. Indemnification</h2>
            <p>You agree to defend and hold harmless AutoWebIQ Inc., its employees, and affiliates from claims arising from:</p>
            <ul>
              <li>Your use of the Services</li>
              <li>Your generated Content</li>
              <li>Your breach of these Terms</li>
            </ul>
          </section>

          <section className="terms-section">
            <h2>13. Miscellaneous</h2>
            <ul>
              <li><strong>Governing Law:</strong> Laws of the State of California.</li>
              <li><strong>Dispute Resolution:</strong> Alameda County, California courts have exclusive jurisdiction.</li>
              <li><strong>Entire Agreement:</strong> These Terms + Privacy Policy constitute the full agreement.</li>
              <li><strong>Modifications:</strong> We may update Terms; continued use implies acceptance.</li>
              <li><strong>Force Majeure:</strong> We're not liable for events beyond our control (e.g., natural disasters, war, Internet failures).</li>
            </ul>
          </section>

          <section className="terms-section">
            <h2>14. Contact Information</h2>
            <p>📧 <strong>Email:</strong> support@autowebiq.com</p>
            <p>🏢 <strong>Address:</strong> 2380 Via Espada, Pleasanton, CA 94566, USA</p>
          </section>

          <section className="terms-section">
            <h2>15. Promotions and Feedback</h2>
            <ul>
              <li>Promotions may include separate terms.</li>
              <li>Feedback or suggestions can be freely used by AutoWebIQ without compensation.</li>
            </ul>
          </section>

          <section className="terms-section">
            <h2>16. DMCA Compliance</h2>
            <p>For copyright complaints, email support@autowebiq.com with:</p>
            <ul>
              <li>Identification of the infringing content</li>
              <li>Contact information</li>
              <li>A statement of good faith and accuracy under penalty of perjury</li>
            </ul>
          </section>

          <section className="terms-section">
            <h2>17. Abuse Reporting</h2>
            <p>Report abuse, security issues, or ToS violations to support@autowebiq.com with details and evidence.</p>
            <p>We take reports seriously and investigate promptly.</p>
          </section>

          <div className="last-updated">
            <p><strong>Last Updated:</strong> October 31, 2025</p>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="terms-footer">
        <div className="footer-container-terms">
          <div className="footer-brand">
            <div className="brand-icon">
              <Sparkles size={24} />
            </div>
            <span>AutoWebIQ</span>
          </div>
          <p className="footer-text">© 2025 AutoWebIQ. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default TermsOfService;
